//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package shadowmage.ancient_warfare.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import shadowmage.ancient_warfare.common.crafting.TEAWCrafting;
 
 
public class ModelTable5 extends ModelTEBase
{
 
ModelRenderer tableTop;
ModelRenderer leg1;
ModelRenderer leg2;
ModelRenderer leg3;
ModelRenderer leg4;
ModelRenderer paperLarge;
ModelRenderer hammerHead1;
ModelRenderer hammerClaw1;
ModelRenderer hammerClaw2;
ModelRenderer hammerHead2;
ModelRenderer hammerHead3;
ModelRenderer hammerHandle;
ModelRenderer shotBottom;
ModelRenderer shotMid;
ModelRenderer shotTop;
ModelRenderer shotSide1;
ModelRenderer shotSide2;
ModelRenderer shotSide3;
ModelRenderer shotSide4;
ModelRenderer boxBottom;
ModelRenderer boxSide1;
ModelRenderer boxSide2;
ModelRenderer boxSide3;
ModelRenderer boxSide4;
public ModelTable5(){
  tableTop = new ModelRenderer(this,"tableTop");
  tableTop.setTextureOffset(0,0);
  tableTop.setTextureSize(128,128);
  tableTop.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(tableTop,0.0f, 0.0f, 0.0f);
  tableTop.addBox(-8.0f,-12.0f,-8.0f,16,1,16);
  leg1 = new ModelRenderer(this,"leg1");
  leg1.setTextureOffset(0,18);
  leg1.setTextureSize(128,128);
  leg1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg1,0.0f, 0.0f, 0.0f);
  leg1.addBox(-7.0f,-11.0f,5.0f,2,11,2);
  tableTop.addChild(leg1);
  leg2 = new ModelRenderer(this,"leg2");
  leg2.setTextureOffset(9,18);
  leg2.setTextureSize(128,128);
  leg2.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg2,0.0f, 0.0f, 0.0f);
  leg2.addBox(-7.0f,-11.0f,-7.0f,2,11,2);
  tableTop.addChild(leg2);
  leg3 = new ModelRenderer(this,"leg3");
  leg3.setTextureOffset(18,18);
  leg3.setTextureSize(128,128);
  leg3.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg3,0.0f, 0.0f, 0.0f);
  leg3.addBox(5.0f,-11.0f,-7.0f,2,11,2);
  tableTop.addChild(leg3);
  leg4 = new ModelRenderer(this,"leg4");
  leg4.setTextureOffset(27,18);
  leg4.setTextureSize(128,128);
  leg4.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg4,0.0f, 0.0f, 0.0f);
  leg4.addBox(5.0f,-11.0f,5.0f,2,11,2);
  tableTop.addChild(leg4);
  paperLarge = new ModelRenderer(this,"paperLarge");
  paperLarge.setTextureOffset(65,0);
  paperLarge.setTextureSize(128,128);
  paperLarge.setRotationPoint(0.0f, -12.01f, 0.0f);
  setPieceRotation(paperLarge,0.0f, -0.19198619f, 0.0f);
  paperLarge.addBox(-6.0f,0.0f,-6.0f,12,0,12);
  tableTop.addChild(paperLarge);
  hammerHead1 = new ModelRenderer(this,"hammerHead1");
  hammerHead1.setTextureOffset(36,18);
  hammerHead1.setTextureSize(128,128);
  hammerHead1.setRotationPoint(-5.0f, -12.25f, 5.0f);
  setPieceRotation(hammerHead1,0.09599306f, 0.3665189f, 0.069813065f);
  hammerHead1.addBox(0.0f,-2.0f,0.0f,2,2,1);
  hammerClaw1 = new ModelRenderer(this,"hammerClaw1");
  hammerClaw1.setTextureOffset(36,22);
  hammerClaw1.setTextureSize(128,128);
  hammerClaw1.setRotationPoint(0.125f, -2.25f, 0.0f);
  setPieceRotation(hammerClaw1,3.120892E-9f, -0.26179937f, 0.0f);
  hammerClaw1.addBox(-2.0f,0.0f,0.0f,2,1,1);
  hammerHead1.addChild(hammerClaw1);
  hammerClaw2 = new ModelRenderer(this,"hammerClaw2");
  hammerClaw2.setTextureOffset(36,25);
  hammerClaw2.setTextureSize(128,128);
  hammerClaw2.setRotationPoint(0.125f, -0.75f, 0.0f);
  setPieceRotation(hammerClaw2,3.120892E-9f, -0.26179937f, 0.0f);
  hammerClaw2.addBox(-2.0f,0.0f,0.0f,2,1,1);
  hammerHead1.addChild(hammerClaw2);
  hammerHead2 = new ModelRenderer(this,"hammerHead2");
  hammerHead2.setTextureOffset(36,28);
  hammerHead2.setTextureSize(128,128);
  hammerHead2.setRotationPoint(2.0f, -1.5f, 0.0f);
  setPieceRotation(hammerHead2,0.0f, 0.0f, 0.0f);
  hammerHead2.addBox(0.0f,0.0f,0.0f,1,1,1);
  hammerHead3 = new ModelRenderer(this,"hammerHead3");
  hammerHead3.setTextureOffset(36,31);
  hammerHead3.setTextureSize(128,128);
  hammerHead3.setRotationPoint(0.5f, -0.5f, -0.5f);
  setPieceRotation(hammerHead3,0.0f, 0.0f, 0.0f);
  hammerHead3.addBox(0.0f,0.0f,0.0f,1,2,2);
  hammerHead2.addChild(hammerHead3);
  hammerHead1.addChild(hammerHead2);
  hammerHandle = new ModelRenderer(this,"hammerHandle");
  hammerHandle.setTextureOffset(43,18);
  hammerHandle.setTextureSize(128,128);
  hammerHandle.setRotationPoint(0.5f, -1.5f, -1.0f);
  setPieceRotation(hammerHandle,0.0f, 0.0f, 0.0f);
  hammerHandle.addBox(0.0f,0.0f,-7.5f,1,1,10);
  hammerHead1.addChild(hammerHandle);
  tableTop.addChild(hammerHead1);
  shotBottom = new ModelRenderer(this,"shotBottom");
  shotBottom.setTextureOffset(0,32);
  shotBottom.setTextureSize(128,128);
  shotBottom.setRotationPoint(3.0f, -13.0f, 3.0f);
  setPieceRotation(shotBottom,6.241784E-9f, -0.27925262f, 0.0f);
  shotBottom.addBox(-1.0f,0.0f,-1.0f,2,1,2);
  shotMid = new ModelRenderer(this,"shotMid");
  shotMid.setTextureOffset(0,36);
  shotMid.setTextureSize(128,128);
  shotMid.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotMid,0.0f, 0.0f, 0.0f);
  shotMid.addBox(-1.5f,-2.5f,-1.5f,3,3,3);
  shotBottom.addChild(shotMid);
  shotTop = new ModelRenderer(this,"shotTop");
  shotTop.setTextureOffset(0,43);
  shotTop.setTextureSize(128,128);
  shotTop.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotTop,0.0f, 0.0f, 0.0f);
  shotTop.addBox(-1.0f,-3.0f,-1.0f,2,1,2);
  shotBottom.addChild(shotTop);
  shotSide1 = new ModelRenderer(this,"shotSide1");
  shotSide1.setTextureOffset(13,32);
  shotSide1.setTextureSize(128,128);
  shotSide1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotSide1,0.0f, 0.0f, 0.0f);
  shotSide1.addBox(-2.0f,-2.0f,-1.0f,1,2,2);
  shotBottom.addChild(shotSide1);
  shotSide2 = new ModelRenderer(this,"shotSide2");
  shotSide2.setTextureOffset(13,37);
  shotSide2.setTextureSize(128,128);
  shotSide2.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotSide2,0.0f, 0.0f, 0.0f);
  shotSide2.addBox(1.0f,-2.0f,-1.0f,1,2,2);
  shotBottom.addChild(shotSide2);
  shotSide3 = new ModelRenderer(this,"shotSide3");
  shotSide3.setTextureOffset(13,42);
  shotSide3.setTextureSize(128,128);
  shotSide3.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotSide3,0.0f, 0.0f, 0.0f);
  shotSide3.addBox(-1.0f,-2.0f,-2.0f,2,2,1);
  shotBottom.addChild(shotSide3);
  shotSide4 = new ModelRenderer(this,"shotSide4");
  shotSide4.setTextureOffset(13,46);
  shotSide4.setTextureSize(128,128);
  shotSide4.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(shotSide4,0.0f, 0.0f, 0.0f);
  shotSide4.addBox(-1.0f,-2.0f,1.0f,2,2,1);
  shotBottom.addChild(shotSide4);
  tableTop.addChild(shotBottom);
  boxBottom = new ModelRenderer(this,"boxBottom");
  boxBottom.setTextureOffset(20,32);
  boxBottom.setTextureSize(128,128);
  boxBottom.setRotationPoint(-2.0f, -13.0f, -5.0f);
  setPieceRotation(boxBottom,0.0f, 0.0f, 0.0f);
  boxBottom.addBox(0.0f,0.0f,0.0f,4,1,4);
  boxSide1 = new ModelRenderer(this,"boxSide1");
  boxSide1.setTextureOffset(20,38);
  boxSide1.setTextureSize(128,128);
  boxSide1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(boxSide1,0.0f, 0.0f, 0.0f);
  boxSide1.addBox(-0.5f,-0.5f,-0.5f,5,1,1);
  boxBottom.addChild(boxSide1);
  boxSide2 = new ModelRenderer(this,"boxSide2");
  boxSide2.setTextureOffset(20,41);
  boxSide2.setTextureSize(128,128);
  boxSide2.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(boxSide2,0.0f, 0.0f, 0.0f);
  boxSide2.addBox(-0.5f,-0.5f,3.5f,5,1,1);
  boxBottom.addChild(boxSide2);
  boxSide3 = new ModelRenderer(this,"boxSide3");
  boxSide3.setTextureOffset(20,44);
  boxSide3.setTextureSize(128,128);
  boxSide3.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(boxSide3,0.0f, 0.0f, 0.0f);
  boxSide3.addBox(-0.5f,-0.5f,0.5f,1,1,3);
  boxBottom.addChild(boxSide3);
  boxSide4 = new ModelRenderer(this,"boxSide4");
  boxSide4.setTextureOffset(29,44);
  boxSide4.setTextureSize(128,128);
  boxSide4.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(boxSide4,0.0f, 0.0f, 0.0f);
  boxSide4.addBox(3.5f,-0.5f,0.5f,1,1,3);
  boxBottom.addChild(boxSide4);
  tableTop.addChild(boxBottom);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  tableTop.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }

@Override
public void renderModel(TEAWCrafting te)
  {
  tableTop.render(0.0625f);
  }

@Override
public void renderModel()
  {
  tableTop.render(0.0625f);  
  }
}
