//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package shadowmage.ancient_warfare.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import shadowmage.ancient_warfare.common.crafting.TEAWCrafting;
 
 
public class ModelTable1 extends ModelTEBase
{
 
ModelRenderer tableTop;
ModelRenderer leg1;
ModelRenderer leg2;
ModelRenderer leg3;
ModelRenderer leg4;
ModelRenderer bookBottomCover;
ModelRenderer paper1;
ModelRenderer paper2;
ModelRenderer paper3;
public ModelTable1(){
  tableTop = new ModelRenderer(this,"tableTop");
  tableTop.setTextureOffset(0,0);
  tableTop.setTextureSize(128,128);
  tableTop.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(tableTop,0.0f, 0.0f, 0.0f);
  tableTop.addBox(-8.0f,-14.0f,-8.0f,16,1,16);
  leg1 = new ModelRenderer(this,"leg1");
  leg1.setTextureOffset(0,18);
  leg1.setTextureSize(128,128);
  leg1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg1,0.0f, 0.0f, 0.0f);
  leg1.addBox(-7.0f,-13.0f,5.0f,2,13,2);
  tableTop.addChild(leg1);
  leg2 = new ModelRenderer(this,"leg2");
  leg2.setTextureOffset(9,18);
  leg2.setTextureSize(128,128);
  leg2.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg2,0.0f, 0.0f, 0.0f);
  leg2.addBox(-7.0f,-13.0f,-7.0f,2,13,2);
  tableTop.addChild(leg2);
  leg3 = new ModelRenderer(this,"leg3");
  leg3.setTextureOffset(18,18);
  leg3.setTextureSize(128,128);
  leg3.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg3,0.0f, 0.0f, 0.0f);
  leg3.addBox(5.0f,-13.0f,-7.0f,2,13,2);
  tableTop.addChild(leg3);
  leg4 = new ModelRenderer(this,"leg4");
  leg4.setTextureOffset(27,18);
  leg4.setTextureSize(128,128);
  leg4.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg4,0.0f, 0.0f, 0.0f);
  leg4.addBox(5.0f,-13.0f,5.0f,2,13,2);
  tableTop.addChild(leg4);
  bookBottomCover = new ModelRenderer(this,"bookBottomCover");
  bookBottomCover.setTextureOffset(0,35);
  bookBottomCover.setTextureSize(128,128);
  bookBottomCover.setRotationPoint(-6.0f, -15.01f, -1.0f);
  setPieceRotation(bookBottomCover,0.0f, 0.0f, 0.0f);
  bookBottomCover.addBox(0.0f,0.0f,0.0f,5,1,8);
  tableTop.addChild(bookBottomCover);
  paper1 = new ModelRenderer(this,"paper1");
  paper1.setTextureOffset(65,0);
  paper1.setTextureSize(128,128);
  paper1.setRotationPoint(2.0f, -14.01f, 3.0f);
  setPieceRotation(paper1, 0.f, -0.36651903f, 0.0f);
  paper1.addBox(-2.0f,0.0f,-3.0f,4,0,6);
  tableTop.addChild(paper1);
  paper2 = new ModelRenderer(this,"paper2");
  paper2.setTextureOffset(65,7);
  paper2.setTextureSize(128,128);
  paper2.setRotationPoint(4.0f, -14.02f, -3.0f);
  setPieceRotation(paper2, 0.f, 0.29670596f, 0.0f);
  paper2.addBox(-2.0f,0.0f,-3.0f,4,0,6);
  tableTop.addChild(paper2);
  paper3 = new ModelRenderer(this,"paper3");
  paper3.setTextureOffset(65,14);
  paper3.setTextureSize(128,128);
  paper3.setRotationPoint(-2.0f, -14.01f, -4.0f);
  setPieceRotation(paper3, 0.f, -0.3141596f, 0.0f);
  paper3.addBox(-2.0f,0.0f,-3.0f,4,0,6);
  tableTop.addChild(paper3);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  tableTop.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }

@Override
public void renderModel(TEAWCrafting te)
  {
  tableTop.render(0.0625f);
  }

@Override
public void renderModel()
  {
  tableTop.render(0.0625f);
  }
}
