//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package shadowmage.ancient_warfare.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import shadowmage.ancient_warfare.common.crafting.TEAWCrafting;
 
 
public class ModelTable6 extends ModelTEBase
{
 
ModelRenderer tableTop;
ModelRenderer leg1;
ModelRenderer leg2;
ModelRenderer leg3;
ModelRenderer leg4;
ModelRenderer bookBottomCover;
ModelRenderer bookBottomCover2;
ModelRenderer inkWell;
ModelRenderer inkTop;
ModelRenderer pen;
ModelRenderer penTip1;
ModelRenderer penTip2;
ModelRenderer feather1;
ModelRenderer feather1CP2;
public ModelTable6(){
  tableTop = new ModelRenderer(this,"tableTop");
  tableTop.setTextureOffset(0,0);
  tableTop.setTextureSize(128,128);
  tableTop.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(tableTop,0.0f, 0.0f, 0.0f);
  tableTop.addBox(-8.0f,-14.0f,-8.0f,16,1,16);
  leg1 = new ModelRenderer(this,"leg1");
  leg1.setTextureOffset(0,18);
  leg1.setTextureSize(128,128);
  leg1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg1,0.0f, 0.0f, 0.0f);
  leg1.addBox(-7.0f,-13.0f,5.0f,2,13,2);
  tableTop.addChild(leg1);
  leg2 = new ModelRenderer(this,"leg2");
  leg2.setTextureOffset(9,18);
  leg2.setTextureSize(128,128);
  leg2.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg2,0.0f, 0.0f, 0.0f);
  leg2.addBox(-7.0f,-13.0f,-7.0f,2,13,2);
  tableTop.addChild(leg2);
  leg3 = new ModelRenderer(this,"leg3");
  leg3.setTextureOffset(18,18);
  leg3.setTextureSize(128,128);
  leg3.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg3,0.0f, 0.0f, 0.0f);
  leg3.addBox(5.0f,-13.0f,-7.0f,2,13,2);
  tableTop.addChild(leg3);
  leg4 = new ModelRenderer(this,"leg4");
  leg4.setTextureOffset(27,18);
  leg4.setTextureSize(128,128);
  leg4.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(leg4,0.0f, 0.0f, 0.0f);
  leg4.addBox(5.0f,-13.0f,5.0f,2,13,2);
  tableTop.addChild(leg4);
  bookBottomCover = new ModelRenderer(this,"bookBottomCover");
  bookBottomCover.setTextureOffset(0,35);
  bookBottomCover.setTextureSize(128,128);
  bookBottomCover.setRotationPoint(-2.0f, -15.02f, 2.0f);
  setPieceRotation(bookBottomCover,0.0f, -0.10471985f, 0.0f);
  bookBottomCover.addBox(-5.0f,0.0f,-4.0f,10,1,8);
  bookBottomCover2 = new ModelRenderer(this,"bookBottomCover2");
  bookBottomCover2.setTextureOffset(-9,45);
  bookBottomCover2.setTextureSize(128,128);
  bookBottomCover2.setRotationPoint(0.0f, 0.01f, 0.0f);
  setPieceRotation(bookBottomCover2,0.0f, 0.0f, 0.0f);
  bookBottomCover2.addBox(-5.5f,1.0f,-4.5f,11,0,9);
  bookBottomCover.addChild(bookBottomCover2);
  tableTop.addChild(bookBottomCover);
  inkWell = new ModelRenderer(this,"inkWell");
  inkWell.setTextureOffset(36,18);
  inkWell.setTextureSize(128,128);
  inkWell.setRotationPoint(6.0f, -15.0f, 5.0f);
  setPieceRotation(inkWell,1.2483568E-8f, 0.17453283f, 0.0f);
  inkWell.addBox(-1.0f,0.0f,-1.0f,2,1,2);
  inkTop = new ModelRenderer(this,"inkTop");
  inkTop.setTextureOffset(36,22);
  inkTop.setTextureSize(128,128);
  inkTop.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(inkTop,0.0f, 0.0f, 0.0f);
  inkTop.addBox(-0.5f,-0.5f,-0.5f,1,1,1);
  inkWell.addChild(inkTop);
  tableTop.addChild(inkWell);
  pen = new ModelRenderer(this,"pen");
  pen.setTextureOffset(36,25);
  pen.setTextureSize(128,128);
  pen.setRotationPoint(2.0f, -16.0f, 2.0f);
  setPieceRotation(pen,0.0f, 0.2967059f, 0.0f);
  pen.addBox(-0.5f,0.0f,-1.5f,1,1,2);
  penTip1 = new ModelRenderer(this,"penTip1");
  penTip1.setTextureOffset(36,28);
  penTip1.setTextureSize(128,128);
  penTip1.setRotationPoint(0.0f, 0.5f, 0.5f);
  setPieceRotation(penTip1,-0.78539705f, 0.0f, -0.78539747f);
  penTip1.addBox(0.0f,-0.5f,-0.5f,0,1,1);
  pen.addChild(penTip1);
  penTip2 = new ModelRenderer(this,"penTip2");
  penTip2.setTextureOffset(39,28);
  penTip2.setTextureSize(128,128);
  penTip2.setRotationPoint(0.0f, 0.5f, 0.5f);
  setPieceRotation(penTip2,-0.78539705f, 0.0f, 0.7853982f);
  penTip2.addBox(0.0f,-0.5f,-0.5f,0,1,1);
  pen.addChild(penTip2);
  feather1 = new ModelRenderer(this,"feather1");
  feather1.setTextureOffset(36,30);
  feather1.setTextureSize(128,128);
  feather1.setRotationPoint(0.0f, 0.5f, -3.0f);
  setPieceRotation(feather1,0.0f, 0.0f, 0.0f);
  feather1.addBox(0.0f,-0.5f,-1.5f,0,1,3);
  pen.addChild(feather1);
  feather1CP2 = new ModelRenderer(this,"feather1CP2");
  feather1CP2.setTextureOffset(36,34);
  feather1CP2.setTextureSize(128,128);
  feather1CP2.setRotationPoint(0.0f, 0.5f, -3.0f);
  setPieceRotation(feather1CP2,0.0f, 0.0f, -1.5707964f);
  feather1CP2.addBox(0.0f,-0.5f,-1.5f,0,1,3);
  pen.addChild(feather1CP2);
  tableTop.addChild(pen);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  tableTop.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }

@Override
public void renderModel(TEAWCrafting te)
  {
  tableTop.render(0.0625f);
  }

@Override
public void renderModel()
  {
  tableTop.render(0.0625f);  
  }

}
