package net.shadowmage.ancientwarfare.structure.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import net.minecraftforge.registries.IForgeRegistry;
import net.shadowmage.ancientwarfare.core.util.InjectionTools;
import net.shadowmage.ancientwarfare.structure.AncientWarfareStructure;

@ObjectHolder(AncientWarfareStructure.MOD_ID)
@Mod.EventBusSubscriber(modid = AncientWarfareStructure.MOD_ID)
public class AWStructureSounds {
	public static final SoundEvent PROTECTION_FLAG_CLAIM = InjectionTools.nullValue();
	public static final SoundEvent COFFIN_OPENS = InjectionTools.nullValue();
	public static final SoundEvent URN_BREAK = InjectionTools.nullValue();
	public static final SoundEvent COIN_STACK_BREAK = InjectionTools.nullValue();
	public static final SoundEvent COIN_STACK_INTERACT = InjectionTools.nullValue();
	public static final SoundEvent IRON_GATE = InjectionTools.nullValue();
	public static final SoundEvent IRON_GATE_BREAK = InjectionTools.nullValue();
	public static final SoundEvent WOODEN_GATE = InjectionTools.nullValue();
	public static final SoundEvent WOODEN_GATE_BREAK = InjectionTools.nullValue();
	public static final SoundEvent STONE_COFFIN_OPENS = InjectionTools.nullValue();
	public static final SoundEvent SANDSTONE_SARCOPHAGUS_OPENS = InjectionTools.nullValue();
	public static final SoundEvent PRISMARINE_COFFIN_OPENS = InjectionTools.nullValue();
	public static final SoundEvent DEMONIC_COFFIN_OPENS = InjectionTools.nullValue();

	public static final SoundEvent BARBARIAN_DRUMS_CAUTIOUS = InjectionTools.nullValue();
	public static final SoundEvent BARBARIAN_DRUMS_DISTANT = InjectionTools.nullValue();
	public static final SoundEvent BARBARIAN_DRUMS_SLOW_SHORT = InjectionTools.nullValue();
	public static final SoundEvent BARBARIAN_DRUMS_WARNING = InjectionTools.nullValue();
	public static final SoundEvent BARRACKS_AMBIANCE = InjectionTools.nullValue();
	public static final SoundEvent CLOCK_GRANDFATHER_CHIMES = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_CHITTERING = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_CRYPT_VOICE_1 = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_CRYPT_VOICE_2 = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_CRYPT_VOICE_4 = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_DRONING_1 = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_DRONING_2 = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_EVIL_GIRL = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_GHOSTLY_BREATH = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_GHOSTLY_WHISPER = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_KNOCK_KNOCK = InjectionTools.nullValue();
	public static final SoundEvent CREEPY_SPOOKY_RAVENS = InjectionTools.nullValue();
	public static final SoundEvent CTHULHU = InjectionTools.nullValue();
	public static final SoundEvent CTHULHU_BACKGROUND_1 = InjectionTools.nullValue();
	public static final SoundEvent CTHULHU_BACKGROUND_2 = InjectionTools.nullValue();
	public static final SoundEvent CTHULHU_BACKGROUND_3 = InjectionTools.nullValue();
	public static final SoundEvent DEL_CASHINHAND = InjectionTools.nullValue();
	public static final SoundEvent DEL_COWBOY = InjectionTools.nullValue();
	public static final SoundEvent DEL_DONTBEAPLONKER = InjectionTools.nullValue();
	public static final SoundEvent DEL_DOZYTWONK = InjectionTools.nullValue();
	public static final SoundEvent DEL_GONNABECUSHTY = InjectionTools.nullValue();
	public static final SoundEvent DEL_KEEPYOURMITSOFF = InjectionTools.nullValue();
	public static final SoundEvent DEL_MILLIONARES = InjectionTools.nullValue();
	public static final SoundEvent DEL_MONEYFOROLDROPE = InjectionTools.nullValue();
	public static final SoundEvent DEL_OHSHUTUPYOUTART = InjectionTools.nullValue();
	public static final SoundEvent DEL_PACKITIN = InjectionTools.nullValue();
	public static final SoundEvent DEL_PLONKER = InjectionTools.nullValue();
	public static final SoundEvent DEL_YOUDIPSTICK = InjectionTools.nullValue();
	public static final SoundEvent DEL_YOUPRANNY = InjectionTools.nullValue();
	public static final SoundEvent EMPIRE_CHURCH_BELL = InjectionTools.nullValue();
	public static final SoundEvent EVIL_AMBIENCE_1 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_AMBIENCE_2 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_DARK_PRAYER = InjectionTools.nullValue();
	public static final SoundEvent EVIL_DEMONICHAUNTING1 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_DEMONICHAUNTING2 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_DEMONICHAUNTING3 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_DEMONICHAUNTING4 = InjectionTools.nullValue();
	public static final SoundEvent EVIL_GETOUT = InjectionTools.nullValue();
	public static final SoundEvent GONG_LARGE = InjectionTools.nullValue();
	public static final SoundEvent GONGS_1 = InjectionTools.nullValue();
	public static final SoundEvent GONGS_2 = InjectionTools.nullValue();
	public static final SoundEvent GONGS_3 = InjectionTools.nullValue();
	public static final SoundEvent GONGS_4 = InjectionTools.nullValue();
	public static final SoundEvent GONGS_5 = InjectionTools.nullValue();
	public static final SoundEvent GONGS_6 = InjectionTools.nullValue();
	public static final SoundEvent GRINDSTONE_GENERIC = InjectionTools.nullValue();
	public static final SoundEvent GUARDIANS_CHURCH_CHOIR = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_ENTRY_AMBIENCE = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_TREE_RUSTLING_LEAVES = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_WIND_IN_TREES_01 = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_WIND_IN_TREES_02 = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_WIND_IN_TREES_03 = InjectionTools.nullValue();
	public static final SoundEvent HAUNTED_GRAVEYARD_WIND_IN_TREES_04 = InjectionTools.nullValue();
	public static final SoundEvent HORN_1 = InjectionTools.nullValue();
	public static final SoundEvent HORN_3 = InjectionTools.nullValue();
	public static final SoundEvent HORN_5 = InjectionTools.nullValue();
	public static final SoundEvent HORN_6 = InjectionTools.nullValue();
	public static final SoundEvent HORN_7 = InjectionTools.nullValue();
	public static final SoundEvent HORN_8 = InjectionTools.nullValue();
	public static final SoundEvent JUNGLE_DRUMS_1 = InjectionTools.nullValue();
	public static final SoundEvent JUNGLE_DRUMS_2 = InjectionTools.nullValue();
	public static final SoundEvent LOCATION_SIGH_1 = InjectionTools.nullValue();
	public static final SoundEvent MAGICAL_APPEARANCE = InjectionTools.nullValue();
	public static final SoundEvent MARKET_GENERIC = InjectionTools.nullValue();
	public static final SoundEvent MARKET_GENERIC_2 = InjectionTools.nullValue();
	public static final SoundEvent MYTH_BOLDPREDICTIONS = InjectionTools.nullValue();
	public static final SoundEvent MYTH_PITHHELMET = InjectionTools.nullValue();
	public static final SoundEvent MYTHBUSTERS_EYEBROW = InjectionTools.nullValue();
	public static final SoundEvent MYTHBUSTERS_QUACK = InjectionTools.nullValue();
	public static final SoundEvent MYTHBUSTERS_THERESYOURPROBLEM = InjectionTools.nullValue();
	public static final SoundEvent NOGG_CHURCH_BELLS = InjectionTools.nullValue();
	public static final SoundEvent NOGG_CLOCK_TOWER = InjectionTools.nullValue();
	public static final SoundEvent PIRATE_PUGWASH = InjectionTools.nullValue();
	public static final SoundEvent RELIGIOUS_CHURCH_BELLS_12 = InjectionTools.nullValue();
	public static final SoundEvent SARKONID_MUSIC = InjectionTools.nullValue();
	public static final SoundEvent UNDEAD_AMBIENCE = InjectionTools.nullValue();
	public static final SoundEvent UNDEAD_HAUNTING = InjectionTools.nullValue();
	public static final SoundEvent UNDEAD_SPOOKY = InjectionTools.nullValue();
	public static final SoundEvent UNDEAD_VAMPIRE_EVIL_LAUGH = InjectionTools.nullValue();
	public static final SoundEvent UNDEAD_WHISPERING_VOICES = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_CASTLE_ORGAN_SHORT = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_CRYPT = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_GHOSTLY_VOICES = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_ORGANMUSIC = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_WATCHER = InjectionTools.nullValue();
	public static final SoundEvent VAMPIRE_WHISPERS = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_CARPENTER_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_CARPENTER_2 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_CARPENTER_3 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_CARPENTER_4 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_CARPENTER_5 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_FARM_AMBIENCE_3 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_GENERAL_AMBIENCE_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_GENERAL_AMBIENCE_3 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_LUMBERJACK_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_LUMBERJACK_2 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_MARKET_GENERAL_BACKGROUND_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_PIGEONS_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_PIGEONS_2 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_PIGEONS_3 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_TAVERN_AMBIENT_LOOP = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WATER_MILL_WHEEL_TURNING = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WEAVERS_LOOM = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WELL_CRANK = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WINDMILL = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WINDMILL_INTERIOR = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WINDMILL_SAILS_TURNING_1 = InjectionTools.nullValue();
	public static final SoundEvent VILLAGE_WINDMILL_SAILS_TURNING_2 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_1 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_10 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_2 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_3 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_4 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_5 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_6 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_7 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_8 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_9 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_ERUPTS_1 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_ERUPTS_2 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_ERUPTS_3 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_ERUPTS_4 = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_EXPLOSION = InjectionTools.nullValue();
	public static final SoundEvent VOLCANO_RUMBLE = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_2_CACKLE = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_2_HUNGRY = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_2_LAUGH_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_2_OOOH = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_3 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_4 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_5_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_5_2 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_5_3 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_BUBBLING_CAULDRON_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_BUBBLING_CAULDRON_2 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_BUBBLING_CAULDRON_3 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_BUBBLING_CAULDRON_4 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_BUGS = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_CAT_SCREECHING = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_CROW_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_CROW_2 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_MAD_LAUGH = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_RATS_SQUEAK_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_RATS_SQUEAK_2 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_RATS_SQUEAK_3 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_TOAD_1 = InjectionTools.nullValue();
	public static final SoundEvent WITCH_HOUSE_TOAD_2 = InjectionTools.nullValue();
	public static final SoundEvent WITCHBANE_CHURCH_ENTRY = InjectionTools.nullValue();
	public static final SoundEvent WITCHBANE_NUNS_CHANT = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_EXPLOSION_2 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_1 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_10 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_11 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_12 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_2 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_3 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_4 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_5 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_6 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_7 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_8 = InjectionTools.nullValue();
	public static final SoundEvent WIZARD_TOWER_9 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_13 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_14 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_15 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_16 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_17 = InjectionTools.nullValue();
	public static final SoundEvent WIZARDS_TOWER_18 = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_LONG_DRUM_BEAT = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_PYRAMID_DRUMS = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_TEMPLE_FLUTE = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_TOWN_DRUMS = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_TOWN_FLUTES = InjectionTools.nullValue();
	public static final SoundEvent XOLTEC_TOWN_LONG = InjectionTools.nullValue();
	public static final SoundEvent YO_WAY_YO = InjectionTools.nullValue();
	public static final SoundEvent ZIMBA_DRUMS_2 = InjectionTools.nullValue();
	public static final SoundEvent ZIMBA_VILLAGE_DANCE = InjectionTools.nullValue();
	public static final SoundEvent EVIL_BOOGIEMANCACKLE = InjectionTools.nullValue();

	private AWStructureSounds() {}

	@SubscribeEvent
	public static void register(RegistryEvent.Register<SoundEvent> event) {
		IForgeRegistry<SoundEvent> registry = event.getRegistry();

		registry.register(createSoundEvent("barbarian_drums_cautious"));
		registry.register(createSoundEvent("barbarian_drums_distant"));
		registry.register(createSoundEvent("barbarian_drums_slow_short"));
		registry.register(createSoundEvent("barbarian_drums_warning"));
		registry.register(createSoundEvent("barracks_ambiance"));
		registry.register(createSoundEvent("clock_grandfather_chimes"));
		registry.register(createSoundEvent("coffin_opens"));
		registry.register(createSoundEvent("coin_stack_break"));
		registry.register(createSoundEvent("coin_stack_interact"));
		registry.register(createSoundEvent("creepy_chittering"));
		registry.register(createSoundEvent("creepy_crypt_voice_1"));
		registry.register(createSoundEvent("creepy_crypt_voice_2"));
		registry.register(createSoundEvent("creepy_crypt_voice_4"));
		registry.register(createSoundEvent("creepy_droning_1"));
		registry.register(createSoundEvent("creepy_droning_2"));
		registry.register(createSoundEvent("creepy_evil_girl"));
		registry.register(createSoundEvent("creepy_ghostly_breath"));
		registry.register(createSoundEvent("creepy_ghostly_whisper"));
		registry.register(createSoundEvent("creepy_knock_knock"));
		registry.register(createSoundEvent("creepy_spooky_ravens"));
		registry.register(createSoundEvent("cthulhu"));
		registry.register(createSoundEvent("cthulhu_background_1"));
		registry.register(createSoundEvent("cthulhu_background_2"));
		registry.register(createSoundEvent("cthulhu_background_3"));
		registry.register(createSoundEvent("del_cashinhand"));
		registry.register(createSoundEvent("del_cowboy"));
		registry.register(createSoundEvent("del_dontbeaplonker"));
		registry.register(createSoundEvent("del_dozytwonk"));
		registry.register(createSoundEvent("del_gonnabecushty"));
		registry.register(createSoundEvent("del_keepyourmitsoff"));
		registry.register(createSoundEvent("del_millionares"));
		registry.register(createSoundEvent("del_moneyforoldrope"));
		registry.register(createSoundEvent("del_ohshutupyoutart"));
		registry.register(createSoundEvent("del_packitin"));
		registry.register(createSoundEvent("del_plonker"));
		registry.register(createSoundEvent("del_youdipstick"));
		registry.register(createSoundEvent("del_youpranny"));
		registry.register(createSoundEvent("demonic_coffin_opens"));
		registry.register(createSoundEvent("empire_church_bell"));
		registry.register(createSoundEvent("evil_ambience_1"));
		registry.register(createSoundEvent("evil_ambience_2"));
		registry.register(createSoundEvent("evil_dark_prayer"));
		registry.register(createSoundEvent("evil_demonichaunting1"));
		registry.register(createSoundEvent("evil_demonichaunting2"));
		registry.register(createSoundEvent("evil_demonichaunting3"));
		registry.register(createSoundEvent("evil_demonichaunting4"));
		registry.register(createSoundEvent("evil_getout"));
		registry.register(createSoundEvent("gong_large"));
		registry.register(createSoundEvent("gongs_1"));
		registry.register(createSoundEvent("gongs_2"));
		registry.register(createSoundEvent("gongs_3"));
		registry.register(createSoundEvent("gongs_4"));
		registry.register(createSoundEvent("gongs_5"));
		registry.register(createSoundEvent("gongs_6"));
		registry.register(createSoundEvent("grindstone_generic"));
		registry.register(createSoundEvent("guardians_church_choir"));
		registry.register(createSoundEvent("haunted_graveyard"));
		registry.register(createSoundEvent("haunted_graveyard_entry_ambience"));
		registry.register(createSoundEvent("haunted_graveyard_tree_rustling_leaves"));
		registry.register(createSoundEvent("haunted_graveyard_wind_in_trees_01"));
		registry.register(createSoundEvent("haunted_graveyard_wind_in_trees_02"));
		registry.register(createSoundEvent("haunted_graveyard_wind_in_trees_03"));
		registry.register(createSoundEvent("haunted_graveyard_wind_in_trees_04"));
		registry.register(createSoundEvent("horn_1"));
		registry.register(createSoundEvent("horn_3"));
		registry.register(createSoundEvent("horn_5"));
		registry.register(createSoundEvent("horn_6"));
		registry.register(createSoundEvent("horn_7"));
		registry.register(createSoundEvent("horn_8"));
		registry.register(createSoundEvent("iron_gate"));
		registry.register(createSoundEvent("iron_gate_break"));
		registry.register(createSoundEvent("jungle_drums_1"));
		registry.register(createSoundEvent("jungle_drums_2"));
		registry.register(createSoundEvent("location_sigh_1"));
		registry.register(createSoundEvent("magical_appearance"));
		registry.register(createSoundEvent("market_generic"));
		registry.register(createSoundEvent("market_generic_2"));
		registry.register(createSoundEvent("myth_boldpredictions"));
		registry.register(createSoundEvent("myth_pithhelmet"));
		registry.register(createSoundEvent("mythbusters_eyebrow"));
		registry.register(createSoundEvent("mythbusters_quack"));
		registry.register(createSoundEvent("mythbusters_theresyourproblem"));
		registry.register(createSoundEvent("nogg_church_bells"));
		registry.register(createSoundEvent("nogg_clock_tower"));
		registry.register(createSoundEvent("pirate_pugwash"));
		registry.register(createSoundEvent("prismarine_coffin_opens"));
		registry.register(createSoundEvent("protection_flag_claim"));
		registry.register(createSoundEvent("religious_church_bells_12"));
		registry.register(createSoundEvent("sandstone_sarcophagus_opens"));
		registry.register(createSoundEvent("sarkonid_music"));
		registry.register(createSoundEvent("stone_coffin_opens"));
		registry.register(createSoundEvent("undead_ambience"));
		registry.register(createSoundEvent("undead_haunting"));
		registry.register(createSoundEvent("undead_spooky"));
		registry.register(createSoundEvent("undead_vampire_evil_laugh"));
		registry.register(createSoundEvent("undead_whispering_voices"));
		registry.register(createSoundEvent("urn_break"));
		registry.register(createSoundEvent("vampire_castle_organ_short"));
		registry.register(createSoundEvent("vampire_crypt"));
		registry.register(createSoundEvent("vampire_ghostly_voices"));
		registry.register(createSoundEvent("vampire_organmusic"));
		registry.register(createSoundEvent("vampire_watcher"));
		registry.register(createSoundEvent("vampire_whispers"));
		registry.register(createSoundEvent("village_carpenter_1"));
		registry.register(createSoundEvent("village_carpenter_2"));
		registry.register(createSoundEvent("village_carpenter_3"));
		registry.register(createSoundEvent("village_carpenter_4"));
		registry.register(createSoundEvent("village_carpenter_5"));
		registry.register(createSoundEvent("village_farm_ambience_3"));
		registry.register(createSoundEvent("village_general_ambience_1"));
		registry.register(createSoundEvent("village_general_ambience_3"));
		registry.register(createSoundEvent("village_lumberjack_1"));
		registry.register(createSoundEvent("village_lumberjack_2"));
		registry.register(createSoundEvent("village_market_general_background_1"));
		registry.register(createSoundEvent("village_pigeons_1"));
		registry.register(createSoundEvent("village_pigeons_2"));
		registry.register(createSoundEvent("village_pigeons_3"));
		registry.register(createSoundEvent("village_tavern_ambient_loop"));
		registry.register(createSoundEvent("village_water_mill_wheel_turning"));
		registry.register(createSoundEvent("village_weavers_loom"));
		registry.register(createSoundEvent("village_well_crank"));
		registry.register(createSoundEvent("village_windmill"));
		registry.register(createSoundEvent("village_windmill_interior"));
		registry.register(createSoundEvent("village_windmill_sails_turning_1"));
		registry.register(createSoundEvent("village_windmill_sails_turning_2"));
		registry.register(createSoundEvent("volcano"));
		registry.register(createSoundEvent("volcano_1"));
		registry.register(createSoundEvent("volcano_10"));
		registry.register(createSoundEvent("volcano_2"));
		registry.register(createSoundEvent("volcano_3"));
		registry.register(createSoundEvent("volcano_4"));
		registry.register(createSoundEvent("volcano_5"));
		registry.register(createSoundEvent("volcano_6"));
		registry.register(createSoundEvent("volcano_7"));
		registry.register(createSoundEvent("volcano_8"));
		registry.register(createSoundEvent("volcano_9"));
		registry.register(createSoundEvent("volcano_erupts_1"));
		registry.register(createSoundEvent("volcano_erupts_2"));
		registry.register(createSoundEvent("volcano_erupts_3"));
		registry.register(createSoundEvent("volcano_erupts_4"));
		registry.register(createSoundEvent("volcano_explosion"));
		registry.register(createSoundEvent("volcano_rumble"));
		registry.register(createSoundEvent("witch_house_1"));
		registry.register(createSoundEvent("witch_house_2_cackle"));
		registry.register(createSoundEvent("witch_house_2_hungry"));
		registry.register(createSoundEvent("witch_house_2_laugh_1"));
		registry.register(createSoundEvent("witch_house_2_oooh"));
		registry.register(createSoundEvent("witch_house_3"));
		registry.register(createSoundEvent("witch_house_4"));
		registry.register(createSoundEvent("witch_house_5_1"));
		registry.register(createSoundEvent("witch_house_5_2"));
		registry.register(createSoundEvent("witch_house_5_3"));
		registry.register(createSoundEvent("witch_house_bubbling_cauldron_1"));
		registry.register(createSoundEvent("witch_house_bubbling_cauldron_2"));
		registry.register(createSoundEvent("witch_house_bubbling_cauldron_3"));
		registry.register(createSoundEvent("witch_house_bubbling_cauldron_4"));
		registry.register(createSoundEvent("witch_house_bugs"));
		registry.register(createSoundEvent("witch_house_cat_screeching"));
		registry.register(createSoundEvent("witch_house_crow_1"));
		registry.register(createSoundEvent("witch_house_crow_2"));
		registry.register(createSoundEvent("witch_house_mad_laugh"));
		registry.register(createSoundEvent("witch_house_rats_squeak_1"));
		registry.register(createSoundEvent("witch_house_rats_squeak_2"));
		registry.register(createSoundEvent("witch_house_rats_squeak_3"));
		registry.register(createSoundEvent("witch_house_toad_1"));
		registry.register(createSoundEvent("witch_house_toad_2"));
		registry.register(createSoundEvent("witchbane_church_entry"));
		registry.register(createSoundEvent("witchbane_nuns_chant"));
		registry.register(createSoundEvent("wizard_explosion_2"));
		registry.register(createSoundEvent("wizard_tower_1"));
		registry.register(createSoundEvent("wizard_tower_2"));
		registry.register(createSoundEvent("wizard_tower_3"));
		registry.register(createSoundEvent("wizard_tower_4"));
		registry.register(createSoundEvent("wizard_tower_5"));
		registry.register(createSoundEvent("wizard_tower_6"));
		registry.register(createSoundEvent("wizard_tower_7"));
		registry.register(createSoundEvent("wizard_tower_8"));
		registry.register(createSoundEvent("wizard_tower_9"));
		registry.register(createSoundEvent("wizard_tower_10"));
		registry.register(createSoundEvent("wizard_tower_11"));
		registry.register(createSoundEvent("wizard_tower_12"));
		registry.register(createSoundEvent("wizards_tower_13"));
		registry.register(createSoundEvent("wizards_tower_14"));
		registry.register(createSoundEvent("wizards_tower_15"));
		registry.register(createSoundEvent("wizards_tower_16"));
		registry.register(createSoundEvent("wizards_tower_17"));
		registry.register(createSoundEvent("wizards_tower_18"));
		registry.register(createSoundEvent("wooden_gate"));
		registry.register(createSoundEvent("wooden_gate_break"));
		registry.register(createSoundEvent("xoltec_long_drum_beat"));
		registry.register(createSoundEvent("xoltec_pyramid_drums"));
		registry.register(createSoundEvent("xoltec_temple_flute"));
		registry.register(createSoundEvent("xoltec_town_drums"));
		registry.register(createSoundEvent("xoltec_town_flutes"));
		registry.register(createSoundEvent("xoltec_town_long"));
		registry.register(createSoundEvent("yo_way_yo"));
		registry.register(createSoundEvent("zimba_drums_2"));
		registry.register(createSoundEvent("zimba_village_dance"));
		registry.register(createSoundEvent("evil_boogiemancackle"));
	}

	private static SoundEvent createSoundEvent(String soundName) {
		ResourceLocation registryName = new ResourceLocation(AncientWarfareStructure.MOD_ID, soundName);
		return new SoundEvent(registryName).setRegistryName(registryName);
	}
}
